import 'models.dart';

// gainRates 順序: [chest, back, shoulder, arms, legs, abs]

class ExerciseDatabase {
  static List<Exercise> get all => [
        // ── 胸（Chest） ──────────────────────────────
        Exercise(
          name: '腕立て伏せ',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [2.0, 0.3, 0.8, 1.2, 0.0, 0.5],
        ),
        Exercise(
          name: 'ワイド腕立て',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [2.2, 0.2, 0.6, 0.8, 0.0, 0.4],
        ),
        Exercise(
          name: 'ナロー腕立て',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [1.5, 0.2, 0.4, 1.8, 0.0, 0.3],
        ),
        Exercise(
          name: 'デクライン腕立て',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [2.4, 0.3, 1.0, 1.0, 0.0, 0.4],
        ),
        Exercise(
          name: 'インクライン腕立て',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [1.6, 0.2, 0.7, 0.8, 0.0, 0.3],
        ),
        Exercise(
          name: 'ダンベルプレス',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [2.5, 0.2, 0.8, 1.0, 0.0, 0.3],
        ),
        Exercise(
          name: 'ダンベルフライ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [2.8, 0.0, 0.5, 0.5, 0.0, 0.2],
        ),
        Exercise(
          name: 'アーチャー腕立て',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [2.6, 0.3, 0.7, 1.5, 0.0, 0.4],
        ),
        Exercise(
          name: 'ベンチディップス',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.8, 0.2, 0.8, 2.5, 0.0, 0.3],
        ),
        Exercise(
          name: 'ディップス',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [1.5, 0.3, 1.0, 2.8, 0.0, 0.4],
        ),

        // ── 背中（Back） ─────────────────────────────
        Exercise(
          name: '懸垂（チンアップ）',
          icon: '🧗',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 2.8, 0.8, 1.5, 0.0, 0.5],
        ),
        Exercise(
          name: 'ワイドプルアップ',
          icon: '🧗',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.1, 3.0, 1.0, 1.0, 0.0, 0.4],
        ),
        Exercise(
          name: 'ダンベルロウ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.3, 2.5, 0.5, 1.2, 0.0, 0.3],
        ),
        Exercise(
          name: 'インバーテッドロウ',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.5, 2.2, 0.8, 1.0, 0.0, 0.5],
        ),
        Exercise(
          name: 'スーパーマン',
          icon: '🦸',
          category: ExerciseCategory.strength,
          defaultSeconds: 45,
          gainRates: [0.0, 2.0, 0.8, 0.5, 0.5, 1.5],
        ),
        Exercise(
          name: 'バックエクステンション',
          icon: '🦸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 2.2, 0.3, 0.3, 0.8, 1.2],
        ),
        Exercise(
          name: '懸垂（ナローグリップ）',
          icon: '🧗',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 2.5, 0.6, 1.8, 0.0, 0.4],
        ),
        Exercise(
          name: 'ベントオーバーロウ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.3, 3.0, 0.8, 1.0, 0.3, 0.5],
        ),
        Exercise(
          name: 'シングルアームロウ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 2.8, 0.5, 1.2, 0.0, 0.3],
        ),
        Exercise(
          name: 'グッドモーニング',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 2.5, 0.2, 0.2, 1.0, 1.0],
        ),
        Exercise(
          name: 'シュラッグ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 1.5, 0.8, 0.5, 0.0, 0.2],
        ),

        // ── 肩（Shoulders） ──────────────────────────
        Exercise(
          name: 'パイクプッシュアップ',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.5, 0.3, 2.5, 1.0, 0.0, 0.3],
        ),
        Exercise(
          name: 'ダンベルショルダープレス',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.3, 0.2, 2.8, 1.2, 0.0, 0.2],
        ),
        Exercise(
          name: 'サイドレイズ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 45,
          gainRates: [0.0, 0.0, 3.0, 0.5, 0.0, 0.0],
        ),
        Exercise(
          name: 'フロントレイズ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 45,
          gainRates: [0.5, 0.0, 2.5, 0.5, 0.0, 0.0],
        ),
        Exercise(
          name: 'ウォールハンドスタンド',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 30,
          gainRates: [0.5, 0.5, 3.0, 0.8, 0.0, 0.5],
        ),
        Exercise(
          name: 'フェイスプル',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 1.0, 2.0, 0.8, 0.0, 0.2],
        ),
        Exercise(
          name: 'ハンドスタンドプッシュアップ',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 45,
          gainRates: [1.0, 0.5, 3.2, 1.5, 0.0, 0.5],
        ),
        Exercise(
          name: 'アーノルドプレス',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.5, 0.2, 3.0, 1.0, 0.0, 0.2],
        ),
        Exercise(
          name: 'リアデルトフライ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 1.2, 2.5, 0.5, 0.0, 0.2],
        ),
        Exercise(
          name: 'アップライトロウ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.8, 2.2, 1.0, 0.0, 0.2],
        ),

        // ── 腕（Arms） ───────────────────────────────
        Exercise(
          name: 'ダンベルカール',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.3, 0.0, 0.3, 3.0, 0.0, 0.0],
        ),
        Exercise(
          name: 'ハンマーカール',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 0.0, 0.2, 2.8, 0.0, 0.0],
        ),
        Exercise(
          name: 'トライセップスディップス',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.5, 0.2, 0.5, 2.5, 0.0, 0.2],
        ),
        Exercise(
          name: 'ダンベルトライセップス',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.3, 2.8, 0.0, 0.0],
        ),
        Exercise(
          name: 'クローズグリップ腕立て',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [1.2, 0.2, 0.5, 2.2, 0.0, 0.3],
        ),
        Exercise(
          name: 'リバースカール',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.0, 2.5, 0.0, 0.0],
        ),
        Exercise(
          name: 'ダイヤモンドプッシュアップ',
          icon: '🤸',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [1.0, 0.2, 0.5, 3.0, 0.0, 0.3],
        ),
        Exercise(
          name: 'スカルクラッシャー',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.3, 3.0, 0.0, 0.0],
        ),
        Exercise(
          name: 'オーバーヘッドトライセップ',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.5, 3.0, 0.0, 0.0],
        ),

        // ── 脚（Legs） ───────────────────────────────
        Exercise(
          name: 'スクワット',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.5, 0.0, 0.2, 3.0, 0.5],
        ),
        Exercise(
          name: 'ジャンプスクワット',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.2, 3.2, 0.5],
        ),
        Exercise(
          name: 'ブルガリアンスクワット',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 3.5, 0.3],
        ),
        Exercise(
          name: 'ランジ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 3.0, 0.3],
        ),
        Exercise(
          name: 'カーフレイズ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.0, 0.0, 2.5, 0.0],
        ),
        Exercise(
          name: 'グルートブリッジ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.5, 0.0, 0.0, 2.5, 1.0],
        ),
        Exercise(
          name: 'ヒップスラスト',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.8, 0.0, 0.0, 3.0, 0.8],
        ),
        Exercise(
          name: 'シングルレッグデッドリフト',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 1.5, 0.3, 0.0, 2.5, 0.8],
        ),
        Exercise(
          name: 'リバースランジ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 3.0, 0.3],
        ),
        Exercise(
          name: 'ウォーキングランジ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 3.2, 0.4],
        ),
        Exercise(
          name: 'サイドランジ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.0, 0.0, 2.8, 0.3],
        ),
        Exercise(
          name: 'スプリットスクワット',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 3.3, 0.4],
        ),
        Exercise(
          name: 'ルーマニアンデッドリフト',
          icon: '🏋️',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 2.0, 0.0, 0.0, 2.5, 0.5],
        ),
        Exercise(
          name: 'ドンキーキック',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.5, 0.0, 0.0, 2.5, 0.8],
        ),
        Exercise(
          name: 'ステップアップ',
          icon: '🦵',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 3.0, 0.4],
        ),

        // ── 腹筋（Abs） ──────────────────────────────
        Exercise(
          name: 'クランチ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.0, 0.0, 0.0, 3.0],
        ),
        Exercise(
          name: 'プランク',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.3, 0.5, 0.3, 0.2, 0.3, 2.5],
        ),
        Exercise(
          name: 'サイドプランク',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 45,
          gainRates: [0.2, 0.3, 0.5, 0.3, 0.2, 2.8],
        ),
        Exercise(
          name: 'レッグレイズ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.0, 0.0, 0.5, 3.0],
        ),
        Exercise(
          name: 'バイシクルクランチ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.0, 0.0, 0.5, 3.2],
        ),
        Exercise(
          name: 'マウンテンクライマー',
          icon: '🌀',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.3, 0.3, 0.3, 0.3, 1.0, 2.5],
        ),
        Exercise(
          name: 'ロシアンツイスト',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.0, 0.5, 0.0, 3.0],
        ),
        Exercise(
          name: 'Vシットアップ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 0.0, 0.0, 0.2, 0.5, 3.5],
        ),
        Exercise(
          name: 'ドラゴンフラッグ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 45,
          gainRates: [0.5, 0.5, 0.2, 0.5, 0.8, 3.8],
        ),
        Exercise(
          name: 'シットアップ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 0.0, 0.0, 0.2, 0.0, 3.0],
        ),
        Exercise(
          name: 'ハンギングニーレイズ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.5, 0.0, 3.2],
        ),
        Exercise(
          name: 'デッドバグ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 0.3, 0.2, 0.3, 0.3, 2.8],
        ),
        Exercise(
          name: 'バードドッグ',
          icon: '🌀',
          category: ExerciseCategory.strength,
          defaultSeconds: 60,
          gainRates: [0.2, 0.8, 0.3, 0.3, 0.5, 2.5],
        ),

        // ── 有酸素（Cardio） ─────────────────────────
        Exercise(
          name: 'その場ジョギング',
          icon: '🏃',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.0, 0.0, 1.5, 0.5],
        ),
        Exercise(
          name: 'ジャンピングジャック',
          icon: '⬆️',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.3, 0.2, 0.5, 0.2, 1.2, 0.3],
        ),
        Exercise(
          name: 'バーピー',
          icon: '🏋️',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.8, 0.5, 0.5, 0.5, 1.5, 1.0],
        ),
        Exercise(
          name: 'ハイニー',
          icon: '🏃',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.0, 0.0, 1.8, 0.8],
        ),
        Exercise(
          name: 'ボックスジャンプ',
          icon: '⬆️',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.0, 0.3, 0.0, 0.0, 2.5, 0.5],
        ),
        Exercise(
          name: 'スケーター',
          icon: '⛸️',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.0, 0.2, 0.2, 0.0, 2.0, 0.8],
        ),
        Exercise(
          name: 'ベアクロール',
          icon: '🐻',
          category: ExerciseCategory.move,
          defaultSeconds: 60,
          gainRates: [0.8, 0.8, 0.8, 0.8, 1.0, 1.5],
        ),
        Exercise(
          name: 'ロープスキップ（縄跳び）',
          icon: '🪢',
          category: ExerciseCategory.move,
          defaultSeconds: 120,
          gainRates: [0.0, 0.0, 0.3, 0.2, 2.0, 0.5],
        ),

        // ── ストレッチ ───────────────────────────────
        Exercise(
          name: '全身ストレッチ',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 180,
          gainRates: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
        ),
        Exercise(
          name: '胸のストレッチ',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 60,
          gainRates: [0.5, 0.0, 0.3, 0.0, 0.0, 0.0],
        ),
        Exercise(
          name: '背中のストレッチ',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 60,
          gainRates: [0.0, 0.5, 0.0, 0.0, 0.0, 0.3],
        ),
        Exercise(
          name: '肩甲骨はがし',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 60,
          gainRates: [0.2, 0.3, 0.5, 0.0, 0.0, 0.0],
        ),
        Exercise(
          name: '股関節ストレッチ',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 90,
          gainRates: [0.0, 0.2, 0.0, 0.0, 0.5, 0.3],
        ),
        Exercise(
          name: 'ハムストリングストレッチ',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 60,
          gainRates: [0.0, 0.0, 0.0, 0.0, 0.5, 0.2],
        ),
        Exercise(
          name: '深呼吸',
          icon: '🌬️',
          category: ExerciseCategory.stretch,
          defaultSeconds: 60,
          gainRates: [0.1, 0.1, 0.1, 0.0, 0.0, 0.2],
        ),
        Exercise(
          name: 'ヨガ（太陽礼拝）',
          icon: '🧘',
          category: ExerciseCategory.stretch,
          defaultSeconds: 180,
          gainRates: [0.5, 0.5, 0.5, 0.3, 0.5, 0.5],
        ),
        Exercise(
          name: 'フォームローラー',
          icon: '🌀',
          category: ExerciseCategory.stretch,
          defaultSeconds: 120,
          gainRates: [0.2, 0.2, 0.2, 0.0, 0.3, 0.2],
        ),

        // ── 散歩 ────────────────────────────────────
        Exercise(
          name: '散歩',
          icon: '🚶',
          category: ExerciseCategory.walk,
          defaultSeconds: 300,
          gainRates: [0.0, 0.2, 0.0, 0.0, 1.0, 0.3],
        ),
        Exercise(
          name: 'ウォーキング（速歩）',
          icon: '🚶',
          category: ExerciseCategory.walk,
          defaultSeconds: 600,
          gainRates: [0.0, 0.3, 0.0, 0.0, 1.5, 0.5],
        ),
        Exercise(
          name: 'ランニング',
          icon: '🏃',
          category: ExerciseCategory.walk,
          defaultSeconds: 600,
          gainRates: [0.0, 0.3, 0.0, 0.0, 2.0, 0.8],
        ),
        Exercise(
          name: 'サイクリング',
          icon: '🚴',
          category: ExerciseCategory.walk,
          defaultSeconds: 600,
          gainRates: [0.0, 0.2, 0.0, 0.0, 2.2, 0.5],
        ),
      ];
}
